USE [GD2C2019]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP TABLE [NO_SRTA_E_GATOREI].[FACTURAS_COMPRAS]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[PERMISOS_ROLES]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[CUPONES]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[USUARIOS_ROLES]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[FACTURAS]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[COMPRAS]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[OFERTAS]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[CREDITOS]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[TARJETAS]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[ROLES]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[PERMISOS]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[CLIENTES]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[PROVEEDORES]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[DIRECCIONES]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[USUARIOS]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[RUBROS]
GO
DROP TABLE [NO_SRTA_E_GATOREI].[TIPOS_PAGOS]
GO
DROP SCHEMA [NO_SRTA_E_GATOREI]
GO
DROP PROCEDURE LOGIN_USUARIO
GO
DROP PROCEDURE CREAR_USUARIO_CLIENTE
GO
DROP PROCEDURE CREAR_USUARIO_PROVEEDOR
GO
DROP PROCEDURE CARGAR_CREDITO
GO
DROP PROCEDURE FACTURAR_PROVEEDOR
GO
DROP PROCEDURE INVERTIR_BAJA_LOGICA_CLIENTE
GO
DROP PROCEDURE INVERTIR_BAJA_LOGICA_PROVEEDOR
GO
DROP PROCEDURE INVERTIR_BAJA_LOGICA_ROL
GO 
DROP FUNCTION STRING_SPLIT
GO
DROP PROCEDURE ACTUALIZAR_ROL
GO
DROP PROCEDURE CREAR_ROL
GO
DROP PROCEDURE CREAR_PROVEEDOR