USE [GD2C2019]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO [NO_SRTA_E_GATOREI].[DIRECCIONES]
           ([DIRECCION]
           ,[CIUDAD]
           ,[CODIGO_POSTAL])
    SELECT CLI_DIRECCION, CLI_CIUDAD , NULL 
    FROM [GD_ESQUEMA].[MAESTRA]
	GROUP BY CLI_DIRECCION, CLI_CIUDAD 
GO
INSERT INTO [NO_SRTA_E_GATOREI].[DIRECCIONES]
           ([DIRECCION]
           ,[CIUDAD]
           ,[CODIGO_POSTAL])
    SELECT PROVEE_DOM, PROVEE_CIUDAD , NULL 
    FROM [GD_ESQUEMA].[MAESTRA]
	WHERE PROVEE_DOM IS NOT NULL
	GROUP BY PROVEE_DOM, PROVEE_CIUDAD 
GO
INSERT INTO [NO_SRTA_E_GATOREI].[CLIENTES]
           ([DNI]
           ,[NOMBRE]
           ,[APELLIDO]
           ,[MAIL]
           ,[TELEFONO]
           ,[FECHA_NACIMIENTO]
           ,[USUARIO_ID]
           ,[DIRECCION_ID])
     SELECT M.CLI_DNI, M.CLI_NOMBRE, M.CLI_APELLIDO, M.CLI_MAIL, M.CLI_TELEFONO, M.CLI_FECHA_NAC, NULL , D.DIRECCION_ID
	 FROM [GD_ESQUEMA].[MAESTRA] M INNER JOIN [NO_SRTA_E_GATOREI].[DIRECCIONES] D ON M.CLI_DIRECCION = D.DIRECCION
	 GROUP BY M.CLI_DNI, M.CLI_NOMBRE, M.CLI_APELLIDO, M.CLI_MAIL, M.CLI_TELEFONO, M.CLI_FECHA_NAC, D.DIRECCION_ID
GO
INSERT INTO [NO_SRTA_E_GATOREI].[PROVEEDORES] 
           ([CUIT]
           ,[RAZON_SOCIAL]
           ,[NOMBRE_CONTACTO]
           ,[RUBRO]
           ,[MAIL]
           ,[TELEFONO]
           ,[USUARIO_ID]
           ,[DIRECCION_ID])
    SELECT M.PROVEE_CUIT, M.PROVEE_RS, NULL, M.PROVEE_RUBRO,NULL, M.PROVEE_TELEFONO, NULL , D.DIRECCION_ID
	FROM [GD_ESQUEMA].[MAESTRA] M LEFT JOIN [NO_SRTA_E_GATOREI].[DIRECCIONES] D ON M.PROVEE_DOM = D.DIRECCION
    WHERE PROVEE_CUIT IS NOT NULL -- TODO REVISAR ESTO, SINO TRAE LA PRIMER ROW NULL Y ROMPE, CREO QUE ES PORQUE HAY ROWS SIN PROVEEDORES Y LAS AGRUPA EN NULL
	GROUP BY PROVEE_CUIT, PROVEE_RS,PROVEE_RUBRO, PROVEE_TELEFONO, D.DIRECCION_ID
GO
INSERT INTO [NO_SRTA_E_GATOREI].[OFERTAS]
           ([PRECIO_LISTA]
           ,[PRECIO_OFERTA]
           ,[FECHA_PUBLICACION]
           ,[FECHA_VENCIMIENDO]
           ,[CANTIDAD]
           ,[DESCRIPCION]
           ,[FECHA_COMPRA]
           ,[CODIGO]
           ,[ENTREGADO]
           ,[PROVEDOR_ID])
    SELECT OFERTA_PRECIO, OFERTA_PRECIO_FICTICIO, OFERTA_FECHA, OFERTA_FECHA_VENC, OFERTA_CANTIDAD, OFERTA_DESCRIPCION, 
	OFERTA_FECHA_COMPRA, OFERTA_CODIGO, NULL, P.PROVEEDOR_ID
	FROM [GD_ESQUEMA].[MAESTRA]
	LEFT JOIN [NO_SRTA_E_GATOREI].[PROVEEDORES] P ON P.CUIT = PROVEE_CUIT
	WHERE OFERTA_CODIGO IS NOT NULL --MISMO QUE ARRIBA
	GROUP BY OFERTA_PRECIO, OFERTA_PRECIO_FICTICIO, OFERTA_FECHA, OFERTA_FECHA_VENC, OFERTA_CANTIDAD, OFERTA_DESCRIPCION, 
	OFERTA_FECHA_COMPRA, OFERTA_CODIGO,PROVEEDOR_ID
GO
INSERT INTO [NO_SRTA_E_GATOREI].[COMPRAS]
           ([OFERTA_ID]
           ,[CLIENTE_ID]
           ,[FECHA_COMPRA]
           ,[IMPORTE])
SELECT O.OFERTA_ID, C.CLIENTE_ID,  O.FECHA_COMPRA, M.OFERTA_PRECIO_FICTICIO 
	FROM [GD_ESQUEMA].[MAESTRA] M JOIN [NO_SRTA_E_GATOREI].[OFERTAS] O ON M.OFERTA_CODIGO = O.CODIGO 
	JOIN [NO_SRTA_E_GATOREI].[CLIENTES] C ON M.CLI_DNI = C.DNI
    GROUP BY O.OFERTA_ID,C.CLIENTE_ID,O.FECHA_COMPRA, M.OFERTA_PRECIO_FICTICIO
GO
INSERT INTO [NO_SRTA_E_GATOREI].[FACTURAS]
            ([NUMERO],[FECHA])
    SELECT [FACTURA_NRO], [FACTURA_FECHA]
    FROM [GD_ESQUEMA].[MAESTRA]
    WHERE [FACTURA_NRO] IS NOT NULL
    GROUP BY [FACTURA_NRO],[FACTURA_FECHA]
GO
INSERT INTO [NO_SRTA_E_GATOREI].[FACTURAS_COMPRAS]
            ([FACTURA_ID],[COMPRA_ID])
            SELECT [FACTURA_ID] ,[COMPRA_ID]
            FROM [NO_SRTA_E_GATOREI].[COMPRAS] C
            LEFT JOIN [NO_SRTA_E_GATOREI].[OFERTAS] O ON O.[OFERTA_ID] = C.[OFERTA_ID]
            LEFT JOIN [GD_ESQUEMA].[MAESTRA] M ON O.[CODIGO] = M.[OFERTA_CODIGO]
            LEFT JOIN [NO_SRTA_E_GATOREI].[FACTURAS] F ON M.[FACTURA_NRO] = F.[NUMERO]
            WHERE M.[FACTURA_NRO] IS NOT NULL
            GROUP BY [COMPRA_ID], [FACTURA_ID]
GO
UPDATE [NO_SRTA_E_GATOREI].[FACTURAS]
SET IMPORTE= (SELECT SUM(C.IMPORTE)
				FROM [NO_SRTA_E_GATOREI].[COMPRAS] C,[NO_SRTA_E_GATOREI].[FACTURAS_COMPRAS] FC
				WHERE C.[COMPRA_ID] = FC.[COMPRA_ID]
				AND FC.[FACTURA_ID] = [NO_SRTA_E_GATOREI].[FACTURAS].[FACTURA_ID]
				GROUP BY FC.[FACTURA_ID]);