CREATE TRIGGER [NO_SRTA_E_GATOREI].[ACTUALIZA_MONTO_FACTURA]
ON [NO_SRTA_E_GATOREI].[FACTURAS_COMPRAS]
AFTER INSERT 
AS
BEGIN
UPDATE [NO_SRTA_E_GATOREI].[FACTURAS] 
SET [IMPORTE] = [IMPORTE] + (SELECT C.IMPORTE 
							 FROM [NO_SRTA_E_GATOREI].[COMPRA] C
							 WHERE COMPRA_ID = (SELECT COMPRA_ID FROM INSERTED) )
WHERE FACTURA_ID = (SELECT FACTURA_ID FROM INSERTED )
END
GO
CREATE TRIGGER [NO_SRTA_E_GATOREI].[AGREGAR_IMPORTE_COMPRA]
ON [NO_SRTA_E_GATOREI].[COMPRAS]
AFTER INSERT 
AS
BEGIN
UPDATE [NO_SRTA_E_GATOREI].[COMPRAS] 
SET [IMPORTE] = (SELECT PRECIO_OFERTA 
				 FROM [NO_SRTA_E_GATOREI].[OFERTAS] 
				 WHERE OFERTA_ID = (SELECT OFERTA_ID FROM INSERTED ) )
WHERE COMPRA_ID = (SELECT COMPRA_ID FROM INSERTED )                 
END
GO