CREATE TRIGGER [NO_SRTA_E_GATOREI].[ACTUALIZA_MONTO_FACTURA]
ON [NO_SRTA_E_GATOREI].[FACTURAS_COMPRAS]
AFTER INSERT 
AS
BEGIN
UPDATE [NO_SRTA_E_GATOREI].[FACTURAS] 
SET [IMPORTE] = [IMPORTE] + (SELECT SUM(C.IMPORTE) 
							 FROM [NO_SRTA_E_GATOREI].[COMPRAS] C, [NO_SRTA_E_GATOREI].[FACTURAS_COMPRAS] FC
							 WHERE FC.COMPRA_ID = C.COMPRA_ID
							 AND FC.FACTURA_ID = (SELECT TOP 1 FACTURA_ID FROM INSERTED) )
WHERE FACTURA_ID = (SELECT FACTURA_ID FROM INSERTED )
END
GO
CREATE TRIGGER [NO_SRTA_E_GATOREI].[AGREGAR_IMPORTE_COMPRA]
ON [NO_SRTA_E_GATOREI].[COMPRAS]
AFTER INSERT 
AS
BEGIN
UPDATE [NO_SRTA_E_GATOREI].[COMPRAS] 
SET [IMPORTE] = (SELECT PRECIO_OFERTA 
				 FROM [NO_SRTA_E_GATOREI].[OFERTAS] 
				 WHERE OFERTA_ID = (SELECT OFERTA_ID FROM INSERTED ) )
WHERE COMPRA_ID = (SELECT COMPRA_ID FROM INSERTED )                 
END
GO
CREATE TRIGGER [NO_SRTA_E_GATOREI].[ASIGNAR_ROL_USUARIO]
ON [NO_SRTA_E_GATOREI].[USUARIOS]
AFTER INSERT 
AS
BEGIN
INSERT INTO [NO_SRTA_E_GATOREI].[USUARIOS_ROLES](USUARIO_ID,ROL_ID)
VALUES ((SELECT USUARIO_ID FROM INSERTED),(SELECT ROL_ID FROM [NO_SRTA_E_GATOREI].ROLES WHERE NOMBRE = (SELECT TIPO_USUARIO FROM INSERTED)) )
END
GO